### PR TITLE
Pass along type for serializer call #14

### LINKED ISSUE #14: Request body type not passed to serialization adapter
I hit an issue while testing a custom serialization adapter. The adapter uses `System.Xml.Serialization.XmlSerializer` to perform serialization and deserialization, both transformations require the type to be properly processed (so that appropriate XML namespaces can be used, etc). I discovered however that the generic is `object` instead of the specified class, looking at the source this appears to be due to the generic not being passed along to the generic call.

I'll open a PR with some (hopefully) backward compatible changes to address this limitation next chance I get.

### PR DESCRIPTION
**Pull request by Silic0nS0ldier**
This PR is to resolve #14 , and by virtue of me not having Visual Studio installed is untested. Depending on Azure Pipelines here.

I did briefly look into adding unit tests for this change, however the existing performance test didn't give me much to work with. Which is to say, I would probably end up biting off more than I can chew if I tried, and would effectively be disregarding the the contribution guide clause about keeping PRs decomposed into their smallest possible parts.

Put another way, this is a job for later.

### CODE REVIEW

**Comment by MelbourneDeveloper** [comment]
@Silic0nS0ldier thanks so much. I'll try to get to this soon.

**Comment by Silic0nS0ldier** [comment]
Looking at previous commits to master, it appears to pipeline errors are pre-existing. Assuming you don't get to it first, I'll see if I can get this running locally on the weekend to confirm functionality.

**Comment by MelbourneDeveloper** [comment]
> 
> 
> Looking at previous commits to master, it appears to pipeline errors are pre-existing. Assuming you don't get to it first, I'll see if I can get this running locally on the weekend to confirm functionality.

master and develop are compiling fine.

**Comment by MelbourneDeveloper** [comment]
@Silic0nS0ldier I've merged this in to develop. Thanks!

Please just make sure the code compiles next time.

**Comment by Silic0nS0ldier** [comment]
Thanks @MelbourneDeveloper , I had noticed the issue myself a little while after and made some corrections to permit local compilation. Unfortunately I didn't have the chance to update the PR at the time (most of my non-work Dev happens while travelling in an area with poor reception). I'll see what I can do about addressing what has for me been a recurring issue (in the open source sphere at least).

**Comment by MelbourneDeveloper** [comment]
@Silic0nS0ldier Hi. Just letting you know that this change was included as part of Version 3 which has now been released on NuGet. But serialisation has been overhauled in general.

**Comment by Silic0nS0ldier** [comment]
Cheers, looking forward to using it. Got a nightmare of a SOAP web service to work with which should be made that little bit easier now.

**Comment by MelbourneDeveloper** [comment]
@Silic0nS0ldier please let me know if you have any issues. I'm keen to help wherever possible.

**Pull request closed without merging**
