### PR TITLE
cleanup csproj

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by MelbourneDeveloper** [comment]
@SimonCropp this still has conflicts...

**Comment by SimonCropp** [comment]
fixed

**Comment by MelbourneDeveloper** [comment]
There's an issue with the licensing stuff:

image

**Review by MelbourneDeveloper — APPROVED** [review]
Awesome. Thanks

**Comment by SimonCropp** [comment]
fixed

**Pull request merged**
